name: mskg_gpu
channels:
  - willyd
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cudatoolkit=11.0.3
  - cudnn=8.0.5.39
  - openssl=1.1.1k
  - pip=21.1.3
  - python=3.7.10
  - python_abi=3.7
  - setuptools=49.6.0
  - sqlite=3.36.0
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - absl-py==0.13.0
    - altgraph==0.17
    - astunparse==1.6.3
    - cachetools==4.2.2
    - chardet==4.0.0
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.32.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==4.6.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - pefile==2021.5.24
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyinstaller==4.3
    - pyinstaller-hooks-contrib==2021.1
    - pysimplegui==4.40.0
    - pywin32-ctypes==0.2.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.7.0
    - segmentation-models==1.0.1
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.0
    - tensorflow_io==0.17.1
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.4.1